-- 每日一句句库表
-- 请在 Supabase SQL Editor 中运行此脚本
-- Supabase: https://supabase.com/dashboard/project/prpyjwxrovckkpzwytgw

CREATE TABLE IF NOT EXISTS daily_quotes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  zh TEXT NOT NULL,
  en TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: 公开读取
ALTER TABLE daily_quotes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON daily_quotes FOR SELECT USING (true);

-- 插入 100 句初始句库
INSERT INTO daily_quotes (category, zh, en, action) VALUES
('成长', '今天不用证明自己很厉害，只要比昨天更清楚一点。', 'You do not need to prove yourself today. Just become a little clearer than yesterday.', '写下今天最重要的一件小事。'),
('成长', '稳定不是每天状态都好，而是状态一般时也能做一点。', 'Consistency means doing a little even on ordinary days.', '完成一��� 10 分钟任务。'),
('成长', '别急着变成别人期待的样子，先把自己的节奏找回来。', 'Do not rush to become what others expect. Return to your own rhythm first.', '给自己 15 分钟安静时间。'),
('成长', '你不是落后了，你只是在重新整理自己的路线。', 'You are not behind. You are reorganizing your path.', '整理一个最近卡住的问题。'),
('成长', '今天先不要追求完美，先让事情发生。', 'Do not chase perfection today. Let the work begin first.', '打开一个任务，先做第一步。'),
('成长', '真正的进步，常常发生在没人看见的重复里。', 'Real progress often happens in unseen repetition.', '重复练习一个你想变好的动作。'),
('成长', '今天的目标不是翻盘，而是恢复一点掌控感。', 'Today''s goal is to regain a little sense of control.', '列出三件你能控制的小事。'),
('成长', '不用等到准备好，准备好往往是在开始之后发生的。', 'Readiness often comes after you begin.', '现在开始，不超过 3 分钟。'),
('成长', '少一点自责，多一点复盘，路会更清楚。', 'Less self-blame, more reflection. The path becomes clearer.', '写下一个可调整的地方。'),
('成长', '你今天完成的小事，会成为未来信任自己的证据。', 'The small thing you finish today becomes evidence that you can trust yourself.', '完成一件很小但真��的事。'),
('成长', '慢一点没关系，关键是不要把自己从生活里放弃掉。', 'Moving slowly is fine. Just do not give up on your own life.', '做一件照顾自己的小事。'),
('成长', '把注意力放回行动上，焦虑会小一点。', 'Bring your attention back to action, and anxiety becomes smaller.', '选一件能立刻开始的事。'),
('成长', '你不需要一次改变人生，只需要今天不原地打转。', 'You do not need to change your whole life at once. Just stop circling today.', '推进一个停滞的任务。'),
('成长', '清醒不是不难过，而是难过时还能看见下一步。', 'Clarity is not the absence of sadness. It is seeing the next step through it.', '写下下一步该做什么。'),
('成长', '真正的自律，是给重要的事留出位置。', 'Real discipline is making room for what matters.', '删掉一个不必要的安排。'),
('成长', '不要用一天的情绪，否定长期的努力。', 'Do not judge long-term effort by one day''s mood.', '回顾一个最近的进步。'),
('成长', '生活变好，常常不是突然突破，而是少一点混乱。', 'Life often gets better not through a breakthrough, but through less chaos.', '整理一个小区域。'),
('成长', '你可以重新开始很多次，每次都算数。', 'You can begin again many times. Every beginning counts.', '重启一个被搁置的小计划。'),
('成长', '不要把低谷当结论，它只是一个阶段。', 'Do not treat a low point as a conclusion. It is only a phase.', '写下一个还可以尝试的方法。'),
('成长', '能持续的节奏，比短暂的爆发更可靠。', 'A sustainable rhythm is more reliable than a short burst.', '把今天的任务减到最小可完成。'),
('成长', '今天先把自己从拖延里拉出来一点。', 'Today, pull yourself a little out of delay.', '设置一个 10 分钟倒计时。'),
('成长', '别急着证明结果，先保护好过程。', 'Do not rush to prove the result. Protect the process first.', '完成今天的固定动作。'),
('成长', '你需要的不是更多压力，而是更清楚的优先级。', 'You do not need more pressure. You need clearer priorities.', '选出今天唯一最重要的事。'),
('成长', '恢复秩序，从一个小决定开始。', 'Order returns through one small decision.', '做一个明确的小决定。'),
('成长', '把自己照顾好，也是长期主义的一部分。', 'Taking care of yourself is part of long-term thinking.', '喝水、走路或早点休息。'),
('成长', '你不是没有方向，只是需要把声音调小一点。', 'You are not directionless. You just need to lower the noise.', '关掉一个干扰源 20 分钟。'),
('成长', '不要等情绪稳定才行动，行动本身会带来稳定。', 'Do not wait for perfect calm to act. Action can create calm.', '做一件能立刻完成的小事。'),
('成长', '真正重要的事，值得用笨办法慢慢做。', 'What truly matters is worth doing slowly, even in simple ways.', '用最朴素的方法推进一步。'),
('成长', '你今天的认真，会慢慢改变你对自己的看法。', 'Your sincerity today will slowly change how you see yourself.', '认真完成一个细节。'),
('成长', '别把一次中断当失败，重新接上就是能力。', 'Do not treat one interruption as failure. Restarting is a skill.', '接上一个中断的习惯。'),
('成长', '真正的改变，通常先从不再骗自己开始。', 'Real change often begins when you stop lying to yourself.', '诚实写下一个真实状态。'),
('成长', '你可以不快，但要诚实地往前。', 'You do not have to be fast. Move forward honestly.', '完成一个真实进展。'),
('成长', '今天不用赢过别人，只要别丢下自己。', 'You do not need to beat others today. Just do not leave yourself behind.', '为自己做一个小选择。'),
('成长', '生活的底气，来自一次次把小事做完。', 'Confidence in life comes from finishing small things again and again.', '收尾一个小任务。'),
('表达', '表达不是天赋，是一次次把模糊想法说清楚的练习。', 'Expression is the practice of making unclear thoughts clear.', '用三句话说清楚一个想法。'),
('表达', '不要急着说得漂亮，先说得真实、清楚、完整。', 'Do not rush to sound impressive. Be true, clear, and complete first.', '录一段 1 分钟口播。'),
('表达', '内容不是把自己包装得完美，而是把真实经验整理得有用。', 'Content is not perfect packaging. It is useful organization of lived experience.', '写一个今天的小观察。'),
('表达', '一个好选题，往往来自你反复遇到的问题。', 'A good topic often comes from a problem you keep meeting.', '记录一个反复出现的问题。'),
('表达', '先讲清楚，再讲好听；先有结构，再有风格。', 'Be clear before being elegant. Build structure before style.', '把一个想法拆成三点。'),
('表达', '你的生活不是素材库，它先是你正在认真经历的人生。', 'Your life is not just content material. It is a life being sincerely lived.', '写一条不发布的生活记录。'),
('表达', '不要为了流量改变标签，要为了长期表达找到位置。', 'Do not change your identity for traffic. Find your position for long-term expression.', '写下你不想被误解成什么。'),
('表达', '复盘不是否定自己，是给下一次表达一张地图。', 'Reflection is not self-denial. It is a map for your next expression.', '复盘一个优点和一个可改点。'),
('表达', '真实不是把所有事都说出来，而是说出来的部分不假。', 'Being real does not mean saying everything. It means what you say is not false.', '删掉一句不真实的表达。'),
('表达', '好的表达，不是声音最大，而是让人听懂。', 'Good expression is not the loudest voice. It is being understood.', '把一句话改得更简单。'),
('表达', '你不用一开始就有风格，先有稳定输出。', 'You do not need a style at first. Build steady output first.', '写 100 字，不求完美。'),
('表达', '说不清楚的时候，先问自己到底想帮谁。', 'When you cannot explain clearly, ask who you are trying to help.', '写下这条内容的对象。'),
('表达', '不要把表达变成表演，先把它变成连接。', 'Do not turn expression into performance. Let it become connection first.', '写一句真正想说的话。'),
('表达', '稳定表达的人，不是每天都有灵感，而是会记录。', 'People who express steadily do not have inspiration every day. They record.', '记录三个碎片想法。'),
('表达', '一个观点站得住，靠的是事实、结构和诚实。', 'A strong point stands on facts, structure, and honesty.', '给一个观点补一个事实。'),
('表达', '不要怕内容小，小内容也能承载真实经验。', 'Do not fear small content. Small content can carry real experience.', '写一个今天的细节。'),
('表达', '你说得越具体，别人越容易靠近。', 'The more specific you are, the easier it is for others to come closer.', '把抽象词换成具体场景。'),
('表达', '表达的第一步，是允许自己的想法不成熟。', 'The first step of expression is allowing your thoughts to be unfinished.', '写一个不成熟但真实的想法。'),
('表达', '不要一边写一边审判自己，先写完再修改。', 'Do not judge yourself while writing. Finish first, edit later.', '连续写 5 分钟不删改。'),
('表达', '好内容不是永远正确，而是愿意认真更新。', 'Good content is not always right. It is willing to update seriously.', '更新一个旧观点。'),
('表达', '把经历变成表达，需要一点距离，也需要一点诚实。', 'Turning experience into expression needs some distance and some honesty.', '写下一个经历带来的提醒。'),
('表达', '你的表达可以温柔，但不要含糊。', 'Your expression can be gentle, but it should not be vague.', '把一个观点说得更明确。'),
('表达', '每一次开口，都是在训练自己和世界相处。', 'Every time you speak, you practice meeting the world.', '练习说出一个完整回答。'),
('表达', '不必追热点，先追问自己真正关心什么。', 'You do not have to chase trends. First ask what you truly care about.', '列出三个长期关心的问题。'),
('表达', '表达不只是输出，也是整理自己的方式。', 'Expression is not only output. It is a way to organize yourself.', '用文字整理今天的状态。'),
('表达', '一个稳定账号，来自稳定的人设边界。', 'A stable account comes from stable identity boundaries.', '写下账号不做的三类内容。'),
('表达', '让别人记住你，不靠夸张，靠反复清楚地出现。', 'People remember you not through exaggeration, but through clear repetition.', '重复表达一个核心主题。'),
('表达', '别急着找爆款，先找到自己能长期说的话。', 'Do not rush to find viral topics. Find what you can speak about for a long time.', '写一个长期栏目想法。'),
('表达', '好的口播，不是背稿，是带着结构自然说。', 'Good speaking is not reciting. It is speaking naturally with structure.', '用开头、三点、结尾练一次。'),
('表达', '如果不知道说什么，就从今天真正发生的事开始。', 'If you do not know what to say, start with what really happened today.', '记录一件今天发生的小事。'),
('表达', '你不是没有内容，只是还没学会筛选和命名。', 'You do not lack content. You are learning to select and name it.', '给一个生活片段起标题。'),
('表达', '表达的力量，不在完美，而在持续变清楚。', 'The power of expression is not perfection. It is becoming clearer over time.', '重写一句重要的话。'),
('表达', '先把话说给一个具体的人听，内容会自然变清楚。', 'Speak to one specific person first, and the content becomes clearer.', '写下这条内容是说给谁的。'),
('投资', '投资先问风险，再问收益；先问能否活下来，再问能赚多少。', 'In investing, ask about risk before return. Survival comes before profit.', '检查一个持仓的最大风险。'),
('投资', '市场每天报价，但不每天给答案。', 'The market gives prices every day, but not answers every day.', '少看一次价格，多看一个事实。'),
('投资', '好公司不等于好价格，好故事不等于好投资。', 'A good company is not always a good price. A good story is not always a good investment.', '写下一个标的的估值疑问。'),
('投资', '真正的安全边际，来自理解，而不是安慰自己。', 'A real margin of safety comes from understanding, not self-comfort.', '补充一个没弄懂的数据。'),
('投资', '不要因为涨了才相信，也不要因为跌了才研究。', 'Do not believe only because it rises, and do not research only because it falls.', '更新一条核心事实。'),
('投资', '长期主义不是拿着不动，而���知道什么变化真的重要。', 'Long-term thinking is not doing nothing. It is knowing what changes truly matter.', '区分一个事实变化和情绪变化。'),
('投资', '能力圈不是限制你，而是保护你慢慢变强。', 'Your circle of competence does not limit you. It protects you while you grow.', '标记一个暂时看不懂的领域。'),
('投资', '一次不冲动的放弃，也是一笔好投资。', 'A non-impulsive pass can also be a good investment.', '写下一个今天决定不碰的机会。'),
('投资', '现金不是懒惰，现金有时是等待清晰的选择权。', 'Cash is not laziness. Sometimes it is the option to wait for clarity.', '��查一次仓位舒适度。'),
('投资', '看懂一家公司，比追十个热点更有复利。', 'Understanding one company compounds better than chasing ten trends.', '读一页财报或公司资料。'),
('投资', '价格波动会制造噪音，商业质��才决定时间的朋友是谁。', 'Price movement creates noise. Business quality decides who time helps.', '写下一个长期质量证据。'),
('投资', '买入之前写理由，卖出之前看理由。', 'Write your reasons before buying. Review them before selling.', '补一条买入或观察理由。'),
('投资', '不要把行情当老师，行情有时只是情绪。', 'Do not treat market moves as a teacher. Sometimes they are only emotion.', '找一个非价格事实。'),
('投资', '真正的研究，是把不知道的地方暴露出来。', 'Real research exposes what you do not know.', '列出一个还没回答的问题。'),
('投资', '估值不是精确预测，是防止自己付出太高代价。', 'Valuation is not precise prediction. It protects you from overpaying.', '写下一个合理价格区间。'),
('投资', '越想快速赚钱，越要慢下来检查假设。', 'The more you want quick profit, the more you should slow down and check assumptions.', '检查一个投资假设。'),
('投资', '优秀投资者不是永远正确，而是错误时损失可控。', 'Good investors are not always right. Their mistakes are controllable.', '写下一个止错条件。'),
('投资', '不要让一次盈利掩盖错误过程。', 'Do not let one profit hide a bad process.', '复盘一次赚钱但不严谨的决策。'),
('投资', '不要让一次亏损否定正确流程。', 'Do not let one loss deny a sound process.', '复盘一次亏损里的正确动作。'),
('投资', '研究公司，先看它靠什么赚钱，再看它能不能持续赚钱。', 'When studying a company, first ask how it earns, then whether it can keep earning.', '写下一个公司的盈利来源。'),
('投资', '商业模式越简单，越要看长期壁垒。', 'The simpler the business model, the more you should examine its moat.', '找一个护城河证据。'),
('投资', '不要把别人的确定性，误当成自己的理解。', 'Do not mistake someone else''s confidence for your own understanding.', '用自己的话解释一个标的。'),
('投资', '市场的热闹，不等于机会的质量。', 'Market excitement does not equal opportunity quality.', '给一个热门标的降温分析。'),
('投资', '好的买点，常常需要耐心而不是勇气。', 'A good entry often needs patience more than courage.', '写下等待条件。'),
('投资', '股价会提前反应情绪，财报会慢慢暴露事实。', 'Price may react to emotion early. Financial reports reveal facts slowly.', '看一个关键财务指标。'),
('投资', '不要为了参与感买入，要为了理解和赔率买入。', 'Do not buy for participation. Buy for understanding and odds.', '问自己为什么必须现在买。'),
('投资', '真正的机会，不怕你多问几个问题。', 'A real opportunity can withstand more questions.', '追问一个反方问题。'),
('投资', '仓位表达的是信心，也暴露了承受力。', 'Position size expresses confidence and reveals tolerance.', '检查仓位是否符合承受力。'),
('投资', '不要用短期涨跌，代替长期判断。', 'Do not replace long-term judgment with short-term movement.', '写下一条长期判断��据。'),
('投资', '好的投资记录，会让下一次决策少一点情绪。', 'Good investment notes reduce emotion in the next decision.', '补一条投资笔记。'),
('投资', '风险不是波动本身，而是不知道自己在承担什么。', 'Risk is not volatility itself. Risk is not knowing what you are taking on.', '写下一个隐藏风险。'),
('投资', '真正值得持有的东西，经得起你反复检查。', 'What is truly worth holding can survive repeated examination.', '重新检查一个持仓理由。'),
('投资', '投资里的清醒，来自承认自己可能错。', 'Clarity in investing comes from admitting you may be wrong.', '写下一个会推翻判断的信号。');
